version: '3.1'
services:

  DbFromDocker:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: testHibernateDB
      POSTGRES_LOGIN: postgres
      POSTGRES_PASSWORD: hoxa-95-hoxa
    ports:
      - 5000:5432

  app:
    build: ./
    container_name: 'my_app_gorets'
    ports:
      - 8080:8080
#    environment:
#      JDBC_URL: jdbc:postgresql://localhost:5432
#      POSTGRES_LOGIN: postgres
#      POSTGRES_PASSWORD: hoxa-95-hoxa