server:
  port: 8080
  servlet:
    context-path: /market

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://DbFromDocker:5432/testHibernateDB
    username: postgres
    password: hoxa-95-hoxa

  jpa:
    show-sql: true
    properties:
      hibernate:
#        default_schema: market
        dialect: org.hibernate.dialect.PostgresPlusDialect
        hbm2ddl:
          auto: update
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    encoding: UTF-8
