services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.4
    healthcheck:
      test: [ "CMD", "nc", "-vz", "localhost", "2181" ]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181   #  Указывает ZooKeeper, где прослушивать соединения таких клиентов, как Apache Kafka®.
      ZOOKEEPER_TICK_TIME: 2000     # Значение этого параметра указывает, как часто ZooKeeper будет отправлять тики, чтобы проверить, что все серверы в кластере работают нормально. Более конкретно, параметр ZOOKEEPERTICKTIME определяет время в миллисекундах между тиками.
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:6.2.4
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:            # Определяет порты, которые будут привязаны к контейнеру Kafka для доступа к нему извне.
      - 29092:29092
    healthcheck:      # Секция "healthcheck" и её параметры используются для настройки и проверки состояния брокера Kafka. Эти параметры позволяют контролировать и управлять процессом проверки состояния брокера и его компонентов.
      test: [ "CMD", "nc", "-vz", "localhost", "9092" ]    # Определяет команду или скрипт, который будет выполняться для проверки состояния брокера Kafka. Это может быть команда для проверки доступности брокера, проверки подключения к брокеру или другие пользовательские команды, которые могут быть связаны с проверкой работоспособности брокера.
      interval: 10s   #  Задает интервал времени между запусками теста проверки состояния. Это определяет, с какой частотой будет выполняться проверка состояния брокера. Например, если значение параметра interval установлено в 10 секунд, то тест будет запускаться каждые 10 секунд.
      timeout: 3s     # Определяет максимальное время ожидания для выполнения теста проверки состояния брокера. Если тест не завершается в течение указанного времени, он считается неудачным.
      retries: 3      # Определяет количество попыток выполнения теста проверки состояния брокера в случае, если предыдущая попытка была неудачной. Если тест не проходит успешно, будет предпринята указанное количество повторных попыток до достижения успеха или истечения лимита на количество повторов.

    environment:
      KAFKA_BROKER_ID: 1        #  Когда брокер Kafka запускается в кластере, он должен иметь ID, чтобы другие брокеры и клиенты могли его идентифицировать и обращаться к нему. Этот идентификатор может быть любым числом или строкой, но он должен быть уникальным в пределах кластера.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: OUTSIDE://:29092,INTERNAL://:9092    # Задает адреса и порты, на которых Kafka слушает входящие соединения от клиентов и других брокеров.
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:29092,INTERNAL://kafka:9092   # Определяет адрес и порт, на котором Kafka будет доступен для клиентов. Этот адрес используется для рекламы брокера и должен быть доступен для всех клиентов Kafka.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
