server:
  port: 8081
  servlet:
    context-path: /market

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testHibernateDB
    username:
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: market
        dialect: org.hibernate.dialect.PostgresPlusDialect
        hbm2ddl:
          auto: validate
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    encoding: UTF-8
